import React from "react";
import Layout from "@theme/Layout";
import { BookGrid } from "../components/BooksFeatures/BookGrid";
import styles from "./books.module.css";
import {
  thepersonalmba,
  strategicmindset,
  immediateaction,
  thankGodForFeedback,
  communicationSkillsBible,
  powerfulFocus,
  oneSuccessHabit,
  howToTalkToAnyone,
  dopamineDetox,
  thanksForFeedback,
  radicalCandorRevised,
  dareToLead,
  radicalCandorBoss,
  coachingHabit,
  eightRulesOfLove,
  lifeAndWorkPrinciples,
  surroundedByIdiots,
  surroundedByPsychopaths,
  surroundedBySetbacks,
  surroundedByBadBosses,
  surroundedByNarcissists,
  surroundedByLiars,
  menAreFromMarsWomenAreFromVenus,
  emotionalIntelligence,
  mindset,
  courageToBeDisliked,
  neverSplitTheDifference,
  relentless,
  readPeopleLikeABook,
  howToWinFriends,
  howToStopWorrying,
  teamTopologies,
  fourThousandWeeks,
  almanackOfNavalRavikant,
  dailyStoic,
  howToTalkToAnyone2,
  millionaireFastlane,
  bookOnRentalPropertyInvesting,
  deepWork,
  psychologyOfMoney,
  sameAsEver,
  eightyTwentyPrinciple,
  crucialConversations,
  fineArtOfSmallTalk,
  masterYourTime,
  masterYourBeliefs,
  masterYourDestiny,
  masterYourThinking,
  masterYourEmotions,
  masterYourMotivation,
  // masterYourMindset,
  masterYourFocus,
  philosophy101,
  management101,
  economics101,
  negotiating101,
  psych101,
  americanGovernment101,
  usHistory101,
  stockMarket101,
  accounting101,
  investing101,
  oneHundredOneEssays,
  conciseStrategiesOfWar,
  conciseLawsOfHumanNature,
  dailyLaws,
  concise48LawsOfPower,
  conciseArtOfSeduction,
  ikigai,
  invisibleWomen,
  // atomicHabits,
  // compoundEffect,
  hindusInHinduRashtra,
  corporateChanakya,
  kautileeyaArthshastra,
  chanakyas100BestSutras,
  indiaThatIsBharat,
  bossBasicsOfSanatanSanskriti,
  vaidikDincharya,
  semenRetentionMiracles,
  moneyworks,
  bharatEkNayiSoch,
  srimadBhagavadgitaVolumn1,
  srimadBhagavadgitaVolumn2
} from "./books/covers";

const books = [
  {
    id: "1",
    title: "The Personal MBA: Master the art of Business",
    author: "Josh Kaufman",
    cover: thepersonalmba,
    link: "https://amzn.eu/d/gHTts2c",
    reviewSlug: "the-personal-mba",
  },
  {
    id: "2",
    title: "Strategic Mindset: A 7-Day Plan to Identify What Matters",
    author: "Thibaut Meurisse",
    cover: strategicmindset,
    link: "https://amzn.eu/d/8Sq4oUi",
    reviewSlug: "strategic-mindset",
  },
  {
    id: "3",
    title: "Immediate Action: Regain Your Motivation",
    author: "Thibaut Meurisse",
    cover: immediateaction,
    link: "https://amzn.eu/d/05vsULX",
    reviewSlug:
      "immediate-action",
  },
  {
    id: "4",
    title: "Thank God for the Feedback ",
    author: "Sheila Heen & Elaine Lin",
    cover: thankGodForFeedback,
    link: "https://amzn.eu/d/i7UglCO",
    reviewSlug:
      "thank-god-for-the-feedback",
  },
  {
    id: "5",
    title: "The Communication Skills Bible: 30 simple ways to improve your conversations and relationships",
    author: "Lewis J. Korg",
    cover: communicationSkillsBible,
    link: "https://amzn.eu/d/7cCEN6O",
    reviewSlug:
      "the-communication-skills-bible",
  },
  {
    id: "6",
    title:
      "Powerful Focus: A 7-Day Plan to Develop Mental Clarity and Build Strong Focus",
    author: "Thibaut Meurisse",
    cover: powerfulFocus,
    link: "https://amzn.eu/d/fXcqRUB",
    reviewSlug:
      "powerful-focus",
  },
  {
    id: "7",
    title: "The One Success Habit (For Managers)",
    author: "Dr. Fred Ray Lybrand",
    cover: oneSuccessHabit,
    link: "https://amzn.eu/d/hWspkDs",
    reviewSlug: "the-one-success-habit",
  },
  {
    id: "8",
    title: "How to Talk to Anyone and Everyone About Anything",
    author: "Jenny Rick ",
    cover: howToTalkToAnyone,
    link: "https://amzn.eu/d/dlTrXSg",
    reviewSlug:
      "how-to-talk-to-anyone-and-everyone-about-anything",
  },
  {
    id: "9",
    title: "Dopamine Detox",
    author: "Thibaut Meurisse",
    cover: dopamineDetox,
    link: "https://amzn.eu/d/0soRJxY",
    reviewSlug: "dopamine-detox",
  },
  {
    id: "10",
    title: "Thanks for the Feedback: The Science and Art of Receiving Feedback Well",
    author: "Douglas Stone and Sheila Heen ",
    cover: thanksForFeedback,
    link: "https://amzn.eu/d/7uZEdxX",
    reviewSlug: "thanks-for-the-feedback",
  },
  {
    id: "11",
    title: "Radical Candor: How to Get What You Want by Saying What You Mean",
    author: "Kim Scott ",
    cover: radicalCandorRevised,
    link: "https://amzn.eu/d/7KfeSPt",
    reviewSlug: "radical-candor-how-to-get-what-you-want-by-saying-what-you-mean",
  },
  {
    id: "12",
    title: "Dare to Lead: Brave Work. Tough Conversations. Whole Hearts.",
    author: "Brené Brown",
    cover: dareToLead,
    link: "https://amzn.eu/d/3wQEMdZ",
    reviewSlug: "dare-to-lead",
  },
  {
    id: "13",
    title: "Radical Candor: Be a Kick-Ass Boss Without Losing Your Humanity",
    author: "Kim Scott",
    cover: radicalCandorBoss,
    link: "https://amzn.eu/d/6IeIMjP",
    reviewSlug: "radical-candor-be-a-kick-ass-boss-without-losing-your-humanity",
  },
  {
    id: "14",
    title: "The Coaching Habit: Say Less, Ask More & Change the Way You Lead Forever Business Mentoring & Coaching",
    author: "Michael Stanier Bungay",
    cover: coachingHabit,
    link: "https://amzn.eu/d/6ra4niN",
    reviewSlug: "the-coaching-habit",
  },
  {
    id: "15",
    title: "8 Rules of Love by Jay Shetty How to Find It Keep It And Let It Go",
    author: "Jay Shetty ",
    cover: eightRulesOfLove,
    link: "https://amzn.eu/d/2ZH4ZcG",
    reviewSlug: "8-rules-of-love",
  },
  {
    id: "16",
    title: "Principles: Life and Work",
    author: "Ray Dalio",
    cover: lifeAndWorkPrinciples,
    link: "https://amzn.eu/d/iGSNl0W",
    reviewSlug: "principles-life-and-work",
  },
  {
    id: "17",
    title: "Surrounded by Idiots",
    author: "Thomas Erikson",
    cover: surroundedByIdiots,
    link: "https://amzn.eu/d/3POkzuT",
    reviewSlug: "surrounded-by-idiots",
  },
  {
    id: "18",
    title: "Surrounded by Psychopaths",
    author: "Thomas Erikson",
    cover: surroundedByPsychopaths,
    link: "https://amzn.eu/d/emSdTJw",
    reviewSlug: "surrounded-by-psychopaths-by-thomas-erikson",
  },
  {
    id: "19",
    title: "Surrounded by Setbacks",
    author: "Thomas Erikson",
    cover: surroundedBySetbacks,
    link: "https://amzn.eu/d/c1oqvH6",
    reviewSlug: "surrounded-by-setbacks",
  },
  {
    id: "20",
    title: "Surrounded by Bad Bosses",
    author: "Thomas Erikson",
    cover: surroundedByBadBosses,
    link: "https://amzn.eu/d/hUn1o3c",
    reviewSlug: "surrounded-by-bad-bosses",
  },
  {
    id: "21",
    title: "Surrounded by Narcissists",
    author: "Thomas Erikson",
    cover: surroundedByNarcissists,
    link: "https://amzn.eu/d/caDnTBj",
    reviewSlug: "surrounded-by-narcissists",
  },
  {
    id: "22",
    title: "Surrounded by Liars",
    author: "Thomas Erikson",
    cover: surroundedByLiars,
    link: "https://amzn.eu/d/4LHrpne",
    reviewSlug: "surrounded-by-liars",
  },
  {
    id: "23",
    title: "Men Are From Mars, Women Are From Venus",
    author: "John Gray",
    cover: menAreFromMarsWomenAreFromVenus,
    link: "https://amzn.eu/d/1rIu4sH",
    reviewSlug: "men-are-from-mars,-women-are-from-venus",
  },
  {
    id: "24",
    title: "Emotional Intelligence",
    author: "Daniel Goleman",
    cover: emotionalIntelligence,
    link: "https://amzn.eu/d/7MaRVpE",
    reviewSlug: "emotional-intelligence",
  },
  {
    id: "25",
    title: "Mindset The New Psychology Of Success",
    author: "Carol S. Dweck",
    cover: mindset,
    link: "https://amzn.eu/d/06Afeav",
    reviewSlug: "mindset-the-new-psychology-of-success",
  },
  {
    id: "26",
    title: "The Courage To Be Disliked",
    author: "Ichiro Kishimi & Fumitake Koga",
    cover: courageToBeDisliked,
    link: "https://amzn.eu/d/4GWHLbZ",
    reviewSlug: "the-courage-to-be-disliked",
  },
  {
    id: "27",
    title: "Never Split The Difference",
    author: "Chris Voss & Tahl Raz ",
    cover: neverSplitTheDifference,
    link: "https://amzn.eu/d/9sk6aSD",
    reviewSlug: "never-split-the-difference",
  },
  {
    id: "28",
    title: "Relentless: From Good to Great to Unstoppable Books",
    author: "Tim S. Grover",
    cover: relentless,
    link: "https://amzn.eu/d/e8zc9a2",
    reviewSlug: "relentless-from-good-to-great-to-unstoppable-books",
  },
  {
    id: "29",
    title: "Read People Like a Book: How to Analyze, Understand, and Predict Peoples Emotions, Thoughts, Intentions, and Behaviors",
    author: "Patrick King",
    cover: readPeopleLikeABook,
    link: "https://amzn.eu/d/0t70hWb",
    reviewSlug: "read-people-like-a-book",
  },
  {
    id: "30",
    title: "How To Win Friends & Influence People",
    author: "Dale Carnegie",
    cover: howToWinFriends,
    link: "https://amzn.eu/d/73UFUXg",
    reviewSlug: "how-to-win-friends-influence-people",
  },
  {
    id: "31",
    title: "How to Stop Worrying And Start Living",
    author: "Dale Carnegie",
    cover: howToStopWorrying,
    link: "https://amzn.eu/d/3OTR9Qt",
    reviewSlug: "how-to-stop-worrying-and-start-living",
  },
  {
    id: "32",
    title: "Team Topologies: Organizing Business and Technology Teams for Fast Flow",
    author: "Matthew Skelton and Manuel Pais",
    cover: teamTopologies,
    link: "https://amzn.eu/d/4k3eOC7",
    reviewSlug: "team-topologies",
  },
  {
    id: "33",
    title: "Four Thousand Weeks: Time Management for Mortals",
    author: "Oliver Burkeman ",
    cover: fourThousandWeeks,
    link: "https://amzn.eu/d/4excm12",
    reviewSlug: "four-thousand-weeks:-time-management-for-mortals",
  },
  {
    id: "34",
    title: "The Almanack of Naval Ravikant: A Guid To Wealth And Happiness",
    author: "Eric Jorgenson",
    cover: almanackOfNavalRavikant,
    link: "https://amzn.eu/d/a6NFUpp",
    reviewSlug: "the-almanack-of-naval-ravikant",
  },
  {
    id: "35",
    title: "The Daily Stoic 366 Meditations on Wisdom Perseverance and the Art of Living",
    author: "Ryan Holiday and Stephen Hanselman",
    cover: dailyStoic,
    link: "https://amzn.eu/d/7GChdE3",
    reviewSlug: "the-daily-stoic-by-ryan-holiday",
  },
  {
    id: "36",
    title: "How To Talk To Anyone: 92 Little Tricks for Big Success in Relationships Communication & Social Skills",
    author: "Leil Lowndes",
    cover: howToTalkToAnyone2,  
    link: "https://amzn.eu/d/5iClvZf",
    reviewSlug: "how-to-talk-to-anyone",
  },
  {
    id: "37",
    title: "The Millionaire Fastlane",
    author: "MJ DeMarco",
    cover: millionaireFastlane,
    link: "https://amzn.eu/d/dwYisur",
    reviewSlug: "the-millionaire-fastlane",
  },
  {
    id: "38",
    title: "The Book on Rental Property Investing",
    author: "Brandon Turner",
    cover: bookOnRentalPropertyInvesting,
    link: "https://amzn.eu/d/8H7mvFj",
    reviewSlug: "the-book-on-rental-property-investing",
  },
  {
    id: "39",
    title: "Deep Work : Rules for Focused Success in A Distracted World",
    author: "Cal Newport",
    cover: deepWork,
    link: "https://amzn.eu/d/1epooDm",
    reviewSlug: "deep-work-rules-for-focused-success-in-a-distracted-world",
  },
  {
    id: "40",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    cover: psychologyOfMoney,
    link: "https://amzn.eu/d/iPH9pr4",
    reviewSlug: "the-psychology-of-money",
  },
  {
    id: "41",
    title: "Same As Ever Book",
    author: "Morgan Housel",
    cover: sameAsEver,
    link: "https://amzn.eu/d/8cHNr32",
    reviewSlug: "same-as-ever-book",
  },
  {
    id: "42",
    title: "The 80/20 Principle The Secret to Achieving More with Less",
    author: "Richard Koch",
    cover: eightyTwentyPrinciple,
    link: "https://amzn.eu/d/3rZubpz",
    reviewSlug: "the-80-20-principle",
  },
  {
    id: "43",
    title: "Crucial Conversations Tools for Talking When Stakes Are High",
    author: "Joseph Grenny",
    cover: crucialConversations,
    link: "https://amzn.eu/d/ibJZRNY",
    reviewSlug: "crucial-conversations",
  },
  {
    id: "44",
    title: "The Fine Art of Small Talk",
    author: "Debra Fine",
    cover: fineArtOfSmallTalk,
    link: "https://amzn.eu/d/1FXbCEb",
    reviewSlug: "the-fine-art-of-small-talk",
  },
  {
    id: "45",
    title: "Master Your Time",
    author: "Thibaut Meurisse",
    cover: masterYourTime,
    link: "https://amzn.eu/d/dFZ7amn",
    reviewSlug: "master-your-time",
  },
  {
    id: "46",
    title: "Master Your Belifes",
    author: "Thibaut Meurisse",
    cover: masterYourBeliefs,
    link: "https://amzn.eu/d/6zr0TVI",
    reviewSlug: "master-your-belifes",
  },
  {
    id: "47",
    title: "Master Your Destiny",
    author: "Thibaut Meurisse",
    cover: masterYourDestiny,
    link: "https://amzn.eu/d/hmM7q30",
    reviewSlug: "master-your-destiny",
  },
  {
    id: "48",
    title: "Master Your Thinking",
    author: "Thibaut Meurisse",
    cover: masterYourThinking,
    link: "https://amzn.eu/d/iy4LgGy",
    reviewSlug: "master-your-thinking",
  },
  {
    id: "49",
    title: "Master Your Emotions",
    author: "Thibaut Meurisse",
    cover: masterYourEmotions,
    link: "https://amzn.eu/d/hEShJjx",
    reviewSlug: "master-your-emotions",
  },
  {
    id: "50",
    title: "Master Your Motivation",
    author: "Thibaut Meurisse",
    cover: masterYourMotivation,
    link: "https://amzn.eu/d/cWRFunc",
    reviewSlug: "master-your-motivation",
  },
  {
    id: "51",
    title: "Master Your Focus",
    author: "Thibaut Meurisse",
    cover: masterYourFocus,
    link: "https://amzn.eu/d/iJ62hes",
    reviewSlug: "master-your-focus",
  },
  {
    id: "52",
    title: "Philosophy 101",
    author: "Paul Kleinman",
    cover: philosophy101,
    link: "https://amzn.eu/d/9evT5lq",
    reviewSlug: "philosophy-101",
  },
  {
    id: "53",
    title: "Management 101",
    author: "Stephan Soundering",
    cover: management101,
    link: "https://amzn.eu/d/2gjMX0v",
    reviewSlug: "management-101",
  },
  {
    id: "54",
    title: "Economics 101",
    author: "Alfred Mill",
    cover: economics101,
    link: "https://amzn.eu/d/h8ndgh5",
    reviewSlug: "economics-101",
  },
  {
    id: "55",
    title: "Negotiating 101",
    author: "Peter Sander",
    cover: negotiating101,
    link: "https://amzn.eu/d/dcxgO1S",
    reviewSlug: "negotiating-101",
  },
  {
    id: "56",
    title: "PSYCH 101",
    author: "Paul Kleinman",
    cover: psych101,
    link: "https://amzn.eu/d/6m4yZ8g",
    reviewSlug: "psych-101",
  },
  {
    id: "57",
    title: "American Government 101",
    author: "Kathleen Sears",
    cover: americanGovernment101,
    link: "https://amzn.eu/d/exeFkVy",
    reviewSlug: "american-government-101",
  },
  {
    id: "58",
    title: "U.S.History 101",
    author: "Kathleen Sears",
    cover: usHistory101,
    link: "https://amzn.eu/d/7KXz8zG",
    reviewSlug: "u.s.history-101",
  },
  {
    id: "59",
    title: "Stock Market 101",
    author: "Michele Cagan",
    cover: stockMarket101,
    link: "https://amzn.eu/d/8YENMCH",
    reviewSlug: "stock-market-101",
  },
  {
    id: "60",
    title: "Accounting 101",
    author: "Michele Cagan",
    cover: accounting101,
    link: "https://amzn.eu/d/7NCyey5",
    reviewSlug: "accounting-101",
  },
  {
    id: "61",
    title: "Investing 101",
    author: "Michele Cagan CPA",
    cover: investing101,
    link: "https://amzn.eu/d/hR55AAV",
    reviewSlug: "investing-101",
  },
  {
    id: "62",
    title: "101 Essays That Will Change The Way You Think",
    author: "Brianna Wiest",
    cover: oneHundredOneEssays,
    link: "https://amzn.eu/d/dzekaJ2",
    reviewSlug: "101-essays-that-will-change-the-way-you-think",
  },
  {
    id: "63",
    title: "The Concise Strategies of War",
    author: "Robert Greene",
    cover: conciseStrategiesOfWar,
    link: "https://amzn.eu/d/hgafEVJ",
    reviewSlug: "the-concise-strategies-of-war",
  },
  {
    id: "64",
    title: "The Concise Laws of Human Nature",
    author: "Robert Greene",
    cover: conciseLawsOfHumanNature,
    link: "https://amzn.eu/d/08HMrn9",
    reviewSlug: "the-concise-laws-of-human-nature",
  },
  {
    id: "65",
    title: "The Daily Laws",
    author: "Robert Greene",
    cover: dailyLaws,
    link: "https://amzn.eu/d/eYsoek1",
    reviewSlug: "the-daily-laws",
  },
  {
    id: "66",
    title: "The Concise 48 Laws of Power",
    author: "Robert Greene",
    cover: concise48LawsOfPower,
    link: "https://amzn.eu/d/h98fWga",
    reviewSlug: "the-concise-48-laws-of-power",
  },
  {
    id: "67",
    title: "The Concise Art of Seduction",
    author: "Robert Greene",
    cover: conciseArtOfSeduction,
    link: "https://amzn.eu/d/3YtQ65Y",
    reviewSlug: "the-concise-art-of-seduction",
  },
  {
    id: "68",
    title: "Ikigai The Japanese Secret Philosophy for A Happy Healthy",
    author: "Hector Garcia",
    cover: ikigai,
    link: "https://amzn.eu/d/ga64BIK",
    reviewSlug: "ikigai-the-japanese-secret",
  },
  {
    id: "69",
    title: "Invisible Women: Exposing Data Bias in a World Designed for Men",
    author: "Caroline Criado-Perez",
    cover: invisibleWomen,
    link: "https://amzn.eu/d/2ewfmcA",
    reviewSlug: "invisible-women",
  },
  // {
  //   id: "70",
  //   title: "Atomic Habits",
  //   author: "James Clear",
  //   cover: atomicHabits,
  //   link: "https://amzn.eu/d/7IW4kiD",
  //   reviewSlug: "atomic-habits",
  // },
  // {
  //   id: "71",
  //   title: "The Compound Effect",
  //   author: " Darren Hardy LLC ",
  //   cover: compoundEffect,
  //   link: "https://amzn.eu/d/ilAj44R",
  //   reviewSlug: "the-compound-effect",
  // },
  {
    id: "72",
    title: "Hindus in Hindu Rashtra: Eighth-class Citizens and Victims of State-sanctioned Apartheid",
    author: "Anand Ranganathan",
    cover: hindusInHinduRashtra,
    link: "https://amzn.eu/d/eJGZrRY",
    reviewSlug: "hindus-in-hindu-rashtra",
  },
  {
    id: "73",
    title: "Corporate Chanakya",
    author: "Radhakrishnan Pillai",
    cover: corporateChanakya,
    link: "https://amzn.eu/d/9ZRfqvO",
    reviewSlug: "corporate-chanakya",
  },
  {
    id: "74",
    title: "Kautileeya Arthshastra",
    author: "Kautilya",
    cover: kautileeyaArthshastra,
    link: "https://amzn.eu/d/dUlh78X",
    reviewSlug: "kautileeya-arthshastra",
  },
  {
    id: "75",
    title: "Chanakya's 100 Best Sutras: Ageless Wisdom for Unlocking Your Potential and Achieving Your Goals",
    author: "Radhakrishnan Pillai",
    cover: chanakyas100BestSutras,
    link: "https://amzn.eu/d/6vwzI7n",
    reviewSlug: "chanakyas-100-best-sutras",
  },
  {
    id: "76",
    title: "India that is Bharat: Coloniality Civilisation Constitution",
    author: "Deepak J. Sai",
    cover: indiaThatIsBharat,
    link: "https://amzn.eu/d/apQuwNn",
    reviewSlug: "india-that-is-bharat",
  },
  {
    id: "77",
    title: "B.O.S.S. Basics of Sanatan Sanskriti",
    author: "Prateeik Prajapati",
    cover: bossBasicsOfSanatanSanskriti,
    link: "https://amzn.eu/d/7JRuoEm",
    reviewSlug: "boss-basics-of-sanatan-sanskriti",
  },
  {
    id: "78",
    title: "Vaidik Dincharya : Rituals, Routines & Shlokas for ideal life",
    author: "Prateeik Prajapati",
    cover: vaidikDincharya,
    link: "https://www.veducation.world/store/3in1combo",
    reviewSlug: "vaidik-dincharya-rituals",
  },
  {
    id: "79",
    title: "Semen Retention Miracles",
    author: "Prateeik Prajapati",
    cover: semenRetentionMiracles,
    link: "https://amzn.eu/d/h0blfU5",
    reviewSlug: "vaidik-dincharya-rituals",
  },
  {
    id: "80",
    title: "Money Works",
    author: "Prateeik Prajapati",
    cover: moneyworks,
    link: "https://amzn.eu/d/jbrH5Tk",
    reviewSlug: "vaidik-dincharya-rituals",
  },
  {
    id: "81",
    title: "Bharat Ek Nayi Soch",
    author: "Harsh Madhusudan & Rajiv Mantri",
    cover: bharatEkNayiSoch,
    link: "https://amzn.eu/d/1WXcLBV",
    reviewSlug: "vaidik-dincharya-rituals",
  },
  {
    id: "82",
    title: "Shrimad Bhagavad Geeta Volume 1",
    author: "Swami Ramsukhdas",
    cover: srimadBhagavadgitaVolumn1,
    link: "https://amzn.eu/d/gOgAWBt",
    reviewSlug: "vaidik-dincharya-rituals",
  },
  {
    id: "83",
    title: "Shrimad Bhagavad Geeta Volume 2",
    author: "Swami Ramsukhdas",
    cover: srimadBhagavadgitaVolumn2,
    link: "https://amzn.eu/d/7cchVby",
    reviewSlug: "vaidik-dincharya-rituals",
  },
];

export default function Books(): JSX.Element {
  return (
    <Layout
      title="Book Reviews"
      description="Discover my personal book reviews and recommendations"
    >
      <main className={styles.booksContainer}>
        <div className={styles.header}>
          <h1>My Book Reviews</h1>
          <p>Discover the books I've read and my thoughts about them</p>
        </div>
        <BookGrid books={books} />
      </main>
    </Layout>
  );
}
